# Generated by Django 6.1 on 2026-08-25 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_contactmessage_service"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Project",
        ),
    ]
